---
README.md:
    name: "acl-service-provider"
    minor_version: "0.1"
    badges:
        - "[![Build Status](http://drone.etna-alternance.net/github.com/etna-alternance/composer-acl-service-provider/status.svg?branch=master)](http://drone.etna-alternance.net/github.com/etna-alternance/composer-acl-service-provider)"
        - "[![Dependency Status](https://www.versioneye.com/user/projects/53dde6f68e78abc191000057/badge.svg)](https://www.versioneye.com/user/projects/53dde6f68e78abc191000057)"
        - "[![Scrutinizer Code Quality](https://scrutinizer-ci.com/g/etna-alternance/composer-acl-service-provider/badges/quality-score.png?b=master)](https://scrutinizer-ci.com/g/etna-alternance/composer-acl-service-provider/?branch=master)"
